// <auto-generated />
using System;
using Drive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drive.Migrations
{
    [DbContext(typeof(DriveContext))]
    partial class DriveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drive.Data.Models.BaseDirDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseDirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseDirId")
                        .IsUnique();

                    b.ToTable("BaseDirDescriptions");
                });

            modelBuilder.Entity("Drive.Data.Models.BaseDirectory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Author")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.ToTable("BaseDirectories");
                });

            modelBuilder.Entity("Drive.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Drive.Data.Models.UserAccessToBaseDir", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseDirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BaseDirId");

                    b.HasIndex("BaseDirId");

                    b.ToTable("UserAccessToBaseDirs");
                });

            modelBuilder.Entity("Drive.Data.Models.BaseDirDescription", b =>
                {
                    b.HasOne("Drive.Data.Models.BaseDirectory", "BaseDirectory")
                        .WithOne("BaseDirDescription")
                        .HasForeignKey("Drive.Data.Models.BaseDirDescription", "BaseDirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseDirectory");
                });

            modelBuilder.Entity("Drive.Data.Models.BaseDirectory", b =>
                {
                    b.HasOne("Drive.Data.Models.User", "User")
                        .WithMany("BaseDirectories")
                        .HasForeignKey("Author")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Models.UserAccessToBaseDir", b =>
                {
                    b.HasOne("Drive.Data.Models.BaseDirectory", "BaseDirectory")
                        .WithMany("UserAccessToBaseDirs")
                        .HasForeignKey("BaseDirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drive.Data.Models.User", "User")
                        .WithMany("UserAccessToBaseDirs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseDirectory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Drive.Data.Models.BaseDirectory", b =>
                {
                    b.Navigation("BaseDirDescription")
                        .IsRequired();

                    b.Navigation("UserAccessToBaseDirs");
                });

            modelBuilder.Entity("Drive.Data.Models.User", b =>
                {
                    b.Navigation("BaseDirectories");

                    b.Navigation("UserAccessToBaseDirs");
                });
#pragma warning restore 612, 618
        }
    }
}
